### PR TITLE
Add cli

### PR DESCRIPTION
**Pull request by lex-c**
Works with local pip install, but there are still dependency install issues with install from conda build.

### CODE REVIEW

**Comment by lex-c** [comment]
@brendancol This is ready to merge and tested to download examples folder after pip install into clean conda env.

**Comment by giancastro** [comment]
@lex-c , why did you deleted the test fixtures? this will make the test suite fail

**Comment by giancastro** [comment]
@lex-c , could you solve the branch conflicts?

**Comment by lex-c** [comment]
I resolved the conflicts and added back in the fixtures, which must have been removed in one of the recursive builds in working out the versioning and examples cli.

**Comment by giancastro** [comment]
@lex-c, could you build a new module called `commands`? The CLI must allow adding new commands like this one #60.

**Pull request closed without merging**
