### PR TITLE
Add geoprocessing service

### PR DESCRIPTION
**Pull request by rencesar**
#48

### CODE REVIEW

**Comment by brendancol** [comment]
@rencesar make sure to push recent local commits

**Comment by giancastro** [comment]
@rencesar, could you take a look at the branch conflicts?

**Comment by brendancol** [comment]
@giancastro @rencesar let's hold off on this PR.  I'm thinking more about GP services and let's meet next week to discuss...closing for now...

**Comment by brendancol** [comment]
@ianthomas23 let's chat about this one

**Comment by brendancol** [comment]
I want to create an example hooked up to Flume: https://flume.dev/

**Pull request closed without merging**
